#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Management.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class CornJobsPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



            
            #line 3 "..\..\Pages\CornJobsPage.cshtml"
  


            
            #line default
            #line hidden
WriteLiteral("<style>\r\n    .tab-content input[type=number] {\r\n        height: 25px;\r\n        wi" +
"dth: 52px;\r\n    }\r\n</style>\r\n<div>\r\n    <div>\r\n        <!-- Nav tabs -->\r\n      " +
"  <ul class=\"nav nav-tabs\" role=\"tablist\">\r\n            ");



WriteLiteral(@"
            <li role=""presentation"" class=""active"">
                <a href=""#minute"" aria-controls=""minute"" role=""tab"" data-toggle=""tab"">分钟</a>
            </li>
            <li role=""presentation"">
                <a href=""#hour"" aria-controls=""hour"" role=""tab"" data-toggle=""tab"">小时</a>
            </li>
            <li role=""presentation"">
                <a href=""#day"" aria-controls=""day"" role=""tab"" data-toggle=""tab"">日</a>
            </li>
            <li role=""presentation"">
                <a href=""#month"" aria-controls=""month"" role=""tab"" data-toggle=""tab"">月</a>
            </li>
            <li role=""presentation"">
                <a href=""#week"" aria-controls=""week"" role=""tab"" data-toggle=""tab"">周</a>
            </li>
            ");



WriteLiteral(@"
            <li role=""presentation"">
                <a href=""#general"" aria-controls=""general"" role=""tab"" data-toggle=""tab"">常用Cron表达式</a>
            </li>
            <li role=""presentation"">
                <a href=""#cron"" aria-controls=""cron"" role=""tab"" data-toggle=""tab"">Cron表达式解析</a>
            </li>
        </ul>
        <!-- Tab panes -->
        <div class=""tab-content"">
            <!--秒-->
            ");



WriteLiteral("\r\n            <!--分钟-->\r\n            <div role=\"tabpanel\" class=\"tab-pane active\"" +
" id=\"minute\">\r\n                <div class=\"radio\">\r\n                    <label>\r" +
"\n                        <input type=\"radio\" name=\"minuteType\" value=\"All\" check" +
"ed=\"checked\">\r\n                        每分钟 允许的通配符[, - * /]\r\n                    " +
"</label>\r\n                </div>\r\n                <div class=\"radio\">\r\n         " +
"           <label>\r\n                        <input type=\"radio\" name=\"minuteType" +
"\" value=\"Cyclic\">\r\n                        周期从\r\n                        <input t" +
"ype=\"number\" id=\"minuteTypeCyclic_1\" value=\"1\">\r\n                        -\r\n    " +
"                    <input type=\"number\" id=\"minuteTypeCyclic_2\" value=\"2\">\r\n   " +
"                     分钟\r\n                    </label>\r\n                </div>\r\n " +
"               <div class=\"radio\">\r\n                    <label>\r\n               " +
"         <input type=\"radio\" name=\"minuteType\" value=\"Interval\">\r\n              " +
"          从\r\n                        <input type=\"number\" id=\"minuteTypeInterval" +
"_1\" value=\"0\">\r\n                        分钟开始,每\r\n                        <input t" +
"ype=\"number\" id=\"minuteTypeInterval_2\" value=\"1\">\r\n                        分钟执行一" +
"次\r\n                    </label>\r\n                </div>\r\n                <div cl" +
"ass=\"radio\">\r\n                    <label>\r\n                        <input type=\"" +
"radio\" name=\"minuteType\" value=\"Assigned\">\r\n                        指定\r\n        " +
"            </label>\r\n                </div>\r\n                <div style=\"margin" +
"-left: 20px;\">\r\n                    <select id=\"minuteTypeAssigned_1\" data-place" +
"holder=\"选择指定的分钟...\"\r\n                            style=\"width:350px;\" multiple><" +
"/select>\r\n                </div>\r\n            </div>\r\n            <!--小时-->\r\n   " +
"         <div role=\"tabpanel\" class=\"tab-pane\" id=\"hour\">\r\n                <div " +
"class=\"radio\">\r\n                    <label>\r\n                        <input type" +
"=\"radio\" name=\"hourType\" value=\"All\" checked=\"checked\">\r\n                       " +
" 每小时 允许的通配符[, - * /]\r\n                    </label>\r\n                </div>\r\n    " +
"            <div class=\"radio\">\r\n                    <label>\r\n                  " +
"      <input type=\"radio\" name=\"hourType\" value=\"Cyclic\">\r\n                     " +
"   周期从\r\n                        <input type=\"number\" id=\"hourTypeCyclic_1\" value" +
"=\"0\">\r\n                        -\r\n                        <input type=\"number\" i" +
"d=\"hourTypeCyclic_2\" value=\"2\">\r\n                        小时\r\n                   " +
" </label>\r\n                </div>\r\n                <div class=\"radio\">\r\n        " +
"            <label>\r\n                        <input type=\"radio\" name=\"hourType\"" +
" value=\"Interval\">\r\n                        从\r\n                        <input ty" +
"pe=\"number\" id=\"hourTypeInterval_1\" value=\"0\">\r\n                        时开始,每\r\n " +
"                       <input type=\"number\" id=\"hourTypeInterval_2\" value=\"1\">\r\n" +
"                        小时执行一次\r\n                    </label>\r\n                </" +
"div>\r\n                <div class=\"radio\">\r\n                    <label>\r\n        " +
"                <input type=\"radio\" name=\"hourType\" value=\"Assigned\">\r\n         " +
"               指定\r\n                    </label>\r\n                </div>\r\n       " +
"         <div style=\"margin-left: 20px;\">\r\n                    <select id=\"hourT" +
"ypeAssigned_1\" data-placeholder=\"选择指定的小时...\"\r\n                            style=" +
"\"width:350px;\" multiple></select>\r\n                </div>\r\n            </div>\r\n\r" +
"\n            <!--日-->\r\n            <div role=\"tabpanel\" class=\"tab-pane\" id=\"day" +
"\">\r\n                <div class=\"radio\">\r\n                    <label>\r\n          " +
"              <input type=\"radio\" name=\"dayType\" value=\"All\" checked=\"checked\">\r" +
"\n                        每日 允许的通配符[, - * / ");



WriteLiteral(@"]
                    </label>
                </div>
                <div class=""radio"">
                    <label>
                        <input type=""radio"" name=""dayType"" value=""Cyclic"">
                        周期从
                        <input type=""number"" id=""dayTypeCyclic_1"" value=""1"">
                        -
                        <input type=""number"" id=""dayTypeCyclic_2"" value=""2"">
                        日
                    </label>
                </div>
                <div class=""radio"">
                    <label>
                        <input type=""radio"" name=""dayType"" value=""Interval"">
                        从
                        <input type=""number"" id=""dayTypeInterval_1"" value=""1"">
                        日开始,每
                        <input type=""number"" id=""dayTypeInterval_2"" value=""1"">
                        日执行一次
                    </label>
                </div>
                <div class=""radio"">
                    <label>
                        <input type=""radio"" name=""dayType"" value=""Assigned"">
                        指定
                    </label>
                </div>
                <div style=""margin-left: 20px;"">
                    <select id=""dayTypeAssigned_1"" data-placeholder=""选择指定的日...""
                            style=""width:350px;"" multiple></select>
                </div>
                ");



WriteLiteral("\r\n            </div>\r\n\r\n            <!--月-->\r\n            <div role=\"tabpanel\" cl" +
"ass=\"tab-pane\" id=\"month\">\r\n                <div class=\"radio\">\r\n               " +
"     <label>\r\n                        <input type=\"radio\" name=\"monthType\" value" +
"=\"All\" checked=\"checked\">\r\n                        每月 允许的通配符[, - * /]\r\n         " +
"           </label>\r\n                </div>\r\n                <div class=\"radio\">" +
"\r\n                    <label>\r\n                        <input type=\"radio\" name=" +
"\"monthType\" value=\"Cyclic\">\r\n                        周期从\r\n                      " +
"  <input type=\"number\" id=\"monthTypeCyclic_1\" value=\"1\">\r\n                      " +
"  -\r\n                        <input type=\"number\" id=\"monthTypeCyclic_2\" value=\"" +
"2\">\r\n                        月\r\n                    </label>\r\n                </" +
"div>\r\n                <div class=\"radio\">\r\n                    <label>\r\n        " +
"                <input type=\"radio\" name=\"monthType\" value=\"Interval\">\r\n        " +
"                从\r\n                        <input type=\"number\" id=\"monthTypeInt" +
"erval_1\" value=\"1\">\r\n                        月开始,每\r\n                        <inp" +
"ut type=\"number\" id=\"monthTypeInterval_2\" value=\"1\">\r\n                        月执" +
"行一次\r\n                    </label>\r\n                </div>\r\n                <div " +
"class=\"radio\">\r\n                    <label>\r\n                        <input type" +
"=\"radio\" name=\"monthType\" value=\"Assigned\">\r\n                        指定\r\n       " +
"             </label>\r\n                </div>\r\n                <div style=\"margi" +
"n-left: 20px;\">\r\n                    <select id=\"monthTypeAssigned_1\" data-place" +
"holder=\"选择指定的月...\"\r\n                            style=\"width:350px;\" multiple></" +
"select>\r\n                </div>\r\n                ");



WriteLiteral(@"
            </div>

            <!--周-->
            <div role=""tabpanel"" class=""tab-pane"" id=""week"">
                <div class=""radio"">
                    <label>
                        <input type=""radio"" name=""weekType"" value=""All"" checked=""checked"">
                        每周 允许的通配符[, - * / ");



WriteLiteral(@"]
                    </label>
                </div>
                <div class=""radio"">
                    <label>
                        <input type=""radio"" name=""weekType"" value=""Cyclic"">
                        周期从
                        <input type=""number"" id=""weekTypeCyclic_1"" value=""1"">
                        -
                        <input type=""number"" id=""weekTypeCyclic_2"" value=""2"">
                        周
                    </label>
                </div>
                <div class=""radio"">
                    <label>
                        <input type=""radio"" name=""weekType"" value=""WeeksOfWeek"">
                        第
                        <input type=""number"" id=""weekTypeWeeksOfWeek_1"" value=""1"">
                        周 的星期
                        <input type=""number"" id=""weekTypeWeeksOfWeek_2"" value=""1"">
                    </label>
                </div>
                <div class=""radio"">
                    <label>
                        <input type=""radio"" name=""weekType"" value=""Assigned"">
                        指定
                    </label>
                </div>
                <div style=""margin-left: 20px;"">
                    <select id=""weekTypeAssigned_1"" data-placeholder=""选择指定的周...""
                            style=""width:350px;"" multiple></select>
                </div>
                ");



WriteLiteral("\r\n            </div>\r\n            <!--年-->\r\n            ");



WriteLiteral("\r\n            <!--常用Cron表达式-->\r\n            <div role=\"tabpanel\" class=\"tab-pane\"" +
" id=\"general\">\r\n                每分： (* * * * *)<br />\r\n                每时： (0 * " +
"* * *)<br />\r\n                每天： (0 0 * * *)<br />\r\n                每周： (0 0 * " +
"* 1)<br />\r\n                每月： (0 0 1 * *)<br />\r\n                每年： (0 0 1 1 " +
"*)<br />\r\n                <br /><br />\r\n                <b>常用示例</b><br />\r\n     " +
"           0 10 * * * ?--------------------每个小时过10分执行一次<br />\r\n                0" +
" 0/32 8,12 * * ? --------------每天8:32,12:32 执行一次<br />\r\n                0 0/2 * " +
"* * ?-------------------每2分钟执行一次<br />\r\n                0 0 12 * * ?------------" +
"--------在每天中午12：00触发<br />\r\n                0 15 10 ? * *-------------------每天上午" +
"10:15 触发<br />\r\n                0 15 10 * * ?-------------------每天上午10:15 触发<br " +
"/>\r\n                0 15 10 * * ? *-----------------每天上午10:15 触发<br />\r\n        " +
"        0 15 10 * * ? 2005--------------在2005年中的每天上午10:15 触发<br />\r\n            " +
"    0 * 14 * * ?--------------------每天在下午2：00至2：59之间每分钟触发一次<br />\r\n             " +
"   0 0/5 14 * * ?------------------每天在下午2：00至2：59之间每5分钟触发一次<br />\r\n             " +
"   0 0/5 14,18 * * ?---------------每天在下午2：00至2：59和6：00至6：59之间的每5分钟触发一次<br />\r\n  " +
"              0 0-5 14 * * ?------------------每天在下午2：00至2：05之间每分钟触发一次<br />\r\n   " +
"             0 10,44 14 ? 3 WED--------------每三月份的星期三在下午2：00和2：44时触发<br />\r\n    " +
"            0 15 10 ? * MON-FRI-------------从星期一至星期五的每天上午10：15触发<br />\r\n        " +
"        0 15 10 15 * ?------------------在每个月的每15天的上午10：15触发<br />\r\n             " +
"   0 15 10 L * ?-------------------在每个月的最后一天的上午10：15触发<br />\r\n                0 " +
"15 10 ? * 6L------------------在每个月的最后一个星期五的上午10：15触发<br />\r\n                0 15" +
" 10 ? * 6L 2002-2005--------在2002, 2003, 2004 and 2005年的每个月的最后一个星期五的上午10：15触发<br" +
" />\r\n                0 15 10 ? * 6#3-----------------在每个月的第三个星期五的上午10：15触发<br />" +
"\r\n                0 0 12 1/5 * ?------------------从每月的第一天起每过5天的中午12：00时触发<br />\r" +
"\n                0 11 11 11 11 ?-----------------在每个11月11日的上午11：11时触发.<br />\r\n\r\n" +
"\r\n\r\n\r\n                <br /><br />\r\n\r\n                每日0点：0 0 0 * * ?<br />\r\n  " +
"              每周一0点：0 0 0 ? * MON 或者 0 0 0 ? * 2 (注:1=SUN,2=MON,3=TUE,4=WED,5=TH" +
"U,6=FRI,7=SAT)<br />\r\n                每月1日0点： 0 0 0 1 * ?<br />\r\n               " +
" 每年1月1日0点：0 0 0 1 1 ?或者 0 0 0 1 JAN ?(注:1-12月依次是JAN, FEB, MAR, APR, MAY, JUN, JU" +
"L, AUG, SEP, OCT, NOV, DEC)<br />\r\n                2046年8月1日0点：0 0 0 1 8 ? 2046<" +
"br />\r\n\r\n                每隔5秒执行一次：*/5 * * * * ?\r\n\r\n                每隔1分钟执行一次：0 *" +
"/1 * * * ?\r\n\r\n                每天23点执行一次：0 0 23 * * ?\r\n\r\n                每天凌晨1点执行" +
"一次：0 0 1 * * ?\r\n\r\n                每月1号凌晨1点执行一次：0 0 1 1 * ?\r\n\r\n                每月" +
"最后一天23点执行一次：0 0 23 L * ?\r\n\r\n                每周星期天凌晨1点实行一次：0 0 1 ? * L\r\n\r\n       " +
"         在26分、29分、33分执行一次：0 26,29,33 * * * ?\r\n\r\n                每天的0点、13点、18点、21" +
"点都执行一次：0 0 0,13,18,21 * * ?\r\n\r\n                每隔5分钟执行一次：0 0/5 * * * ?\r\n        " +
"        \"0 0 12 * * ?\" 每天中午12点触发\r\n                \"0 15 10 ? * *\" 每天上午10:15触发\r\n " +
"               \"0 15 10 * * ?\" 每天上午10:15触发\r\n                \"0 15 10 * * ? *\" 每天" +
"上午10:15触发\r\n                \"0 15 10 * * ? 2005\" 2005年的每天上午10:15触发\r\n             " +
"   \"0 * 14 * * ?\" 在每天下午2点到下午2:59期间的每1分钟触发\r\n                \"0 0/5 14 * * ?\" 在每天下" +
"午2点到下午2:55期间的每5分钟触发\r\n                \"0 0/5 14,18 * * ?\" 在每天下午2点到2:55期间和下午6点到6:5" +
"5期间的每5分钟触发\r\n                \"0 0-5 14 * * ?\" 在每天下午2点到下午2:05期间的每1分钟触发\r\n          " +
"      \"0 10,44 14 ? 3 WED\" 每年三月的星期三的下午2:10和2:44触发\r\n                \"0 15 10 ? * " +
"MON-FRI\" 周一至周五的上午10:15触发\r\n                \"0 15 10 15 * ?\" 每月15日上午10:15触发\r\n     " +
"           \"0 15 10 L * ?\" 每月最后一日的上午10:15触发\r\n                \"0 15 10 ? * 6L\" 每月" +
"的最后一个星期五上午10:15触发\r\n                \"0 15 10 ? * 6L 2002-2005\" 2002年至2005年的每月的最后一" +
"个星期五上午10:15触发\r\n                \"0 15 10 ? * 6#3\" 每月的第三个星期五上午10:15触发\r\n           " +
" </div>\r\n            <!--Cron表达式解析-->\r\n            <div role=\"tabpanel\" class=\"t" +
"ab-pane\" id=\"cron\">\r\n                验证地址 ");


            
            #line 448 "..\..\Pages\CornJobsPage.cshtml"
                Write(Url.To("/cron?cron=*+*+*+*+*"));

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n                精确到分钟数的五部分格式\r\n<pre>\r\n                    * * * * *\r\n     " +
"               - - - - -\r\n                    | | | | |\r\n                    | |" +
" | | +----- [周]day of week (0 - 6) (Sunday=0)\r\n                    | | | +------" +
"- [月]month (1 - 12)\r\n                    | | +--------- [天]day of month (1 - 31)" +
"\r\n                    | +----------- [时]hour (0 - 23)\r\n                    +----" +
"--------- [分]min (0 - 59)\r\n</pre>\r\n                精确到秒数的六部分格式\r\n<pre>\r\n         " +
"       * * * * * *\r\n                - - - - - -\r\n                | | | | | |\r\n  " +
"              | | | | | +--- [周]day of week (0 - 6) (Sunday=0)\r\n                " +
"| | | | +----- [月]month (1 - 12)\r\n                | | | +------- [天]day of month" +
" (1 - 31)\r\n                | | +--------- [时]hour (0 - 23)\r\n                | +-" +
"---------- [分]min (0 - 59)\r\n                +------------- [秒]sec (0 - 59)\r\n</pr" +
"e>\r\n                特殊字符 意义<br />\r\n                <pre>\r\n                * 表示所有" +
"值；例如，“*”在子表达式（月）里表示每个月的含义，“*”在子表达式（天（星期））表示星期的每一天\r\n                - 表示一个指定的范围；\r" +
"\n                , 表示附加一个可能值；\r\n                / 符号前表示开始时间，符号后表示每次递增的值；\r\n</pre>\r" +
"\n\r\n                <b>Cron 表达式包括以下 7 个字段</b><br />\r\n                <ul class=\"l" +
"ist-unstyled\">\r\n                    <li>格式: [秒] [分] [小时] [日] [月] [周] [年]</li>\r\n " +
"                   <li>\r\n                        <table class=\"table table-hover" +
"\">\r\n                            <tr>\r\n                                <th>序号</th" +
">\r\n                                <th>说明</th>\r\n                                " +
"<th>是否必填</th>\r\n                                <th>允许填写的值</th>\r\n                " +
"                <th>允许的通配符</th>\r\n                            </tr>\r\n            " +
"                <tr>\r\n                                <td>1</td>\r\n              " +
"                  <td>秒</td>\r\n                                <td>是</td>\r\n      " +
"                          <td>0-59</td>\r\n                                <td>, -" +
" * /</td>\r\n                            </tr>\r\n                            <tr>\r\n" +
"                                <td>2</td>\r\n                                <td>" +
"分</td>\r\n                                <td>是</td>\r\n                            " +
"    <td>0-59</td>\r\n                                <td>, - * /</td>\r\n           " +
"                 </tr>\r\n                            <tr>\r\n                      " +
"          <td>3</td>\r\n                                <td>小时</td>\r\n             " +
"                   <td>是</td>\r\n                                <td>0-23</td>\r\n  " +
"                              <td>, - * /</td>\r\n                            </tr" +
">\r\n                            <tr>\r\n                                <td>4</td>\r" +
"\n                                <td>日</td>\r\n                                <td" +
">是</td>\r\n                                <td>0-31</td>\r\n                        " +
"        <td>, - * ? / L W</td>\r\n                            </tr>\r\n             " +
"               <tr>\r\n                                <td>5</td>\r\n               " +
"                 <td>月</td>\r\n                                <td>是</td>\r\n       " +
"                         <td>1-12 or JAN-DEC</td>\r\n                             " +
"   <td>, - * /</td>\r\n                            </tr>\r\n                        " +
"    <tr>\r\n                                <td>6</td>\r\n                          " +
"      <td>周</td>\r\n                                <td>是</td>\r\n                  " +
"              <td>1-7 or SUN-SAT</td>\r\n                                <td>, - *" +
" ? / L #</td>\r\n                            </tr>\r\n                            <t" +
"r>\r\n                                <td>7</td>\r\n                                " +
"<td>年</td>\r\n                                <td>否</td>\r\n                        " +
"        <td>empty 或 1970-2099</td>\r\n                                <td>, - * /<" +
"/td>\r\n                            </tr>\r\n                        </table>\r\n     " +
"               </li>\r\n                </ul>\r\n                <b>通配符说明</b><br />\r" +
"\n                <ol>\r\n                    <li>反斜线（/）字符表示增量值。例如，在秒字段中“5/15”代表从第 " +
"5 秒开始，每 15 秒一次。</li>\r\n                    <li>星号（*）字符是通配字符，表示该字段可以接受任何可能的值（例如:在分" +
"的字段上设置 \"*\",表示每一分钟都会触发）。</li>\r\n                    <li>问号（?）问号表示这个字段不包含具体值。所以，如果指" +
"定月内日期，可以在月内日期字段中插入“?”，表示周内日期值无关紧要。字母 L 字符是 last 的缩写。放在月内日期字段中，表示安排在当月最后一天执行。在周内日" +
"期字段中，如果“L”单独存在，就等于“7”，否则代表当月内周内日期的最后一个实例。所以“0L”表示安排在当月的最后一个星期日执行。</li>\r\n        " +
"            <li>-  表示区间，例如 在小时上设置 \"10-12\",表示 10,11,12点都会触发。</li>\r\n              " +
"      <li>逗号（, ） 表示指定多个值，例如在周字段上设置 \"MON,WED,FRI\" 表示周一，周三和周五触发</li>\r\n            " +
"        <li>井号（#）字符为给定月份指定具体的工作日实例。把“MON#2”放在周内日期字段中，表示把任务安排在当月的第二个星期一。</li>\r\n  " +
"                  <li>L 表示最后的意思。在日字段设置上，表示当月的最后一天(依据当前月份，如果是二月还会依据是否是润年[leap]), " +
"在周字段上表示星期六，相当于\"7\"或\"SAT\"。如果在\"L\"前加上数字，则表示该数据的最后一个。例如在周字段上设置\"6L\"这样的格式,则表示“本月最后一个星期五" +
"\"。</li>\r\n                    <li>W 表示离指定日期的最近那个工作日(周一至周五). 例如在日字段上设置\"15W\"，表示离每月1" +
"5号最近的那个工作日触发。如果15号正好是周六，则找最近的周五(14号)触发, 如果15号是周未，则找最近的下周一(16号)触发.如果15号正好在工作日(周一至" +
"周五)，则就在该天触发。如果指定格式为 \"1W\",它则表示每月1号往后最近的工作日触发。如果1号正是周六，则将在3号下周一触发。(注，\"W\"前只能设置具体的数字" +
",不允许区间\"-\")。</li>\r\n                </ol>\r\n                <p class=\"text-danger\">" +
"注：\'L\'和 \'W\'可以一组合使用。如果在日字段上设置\"LW\"，则表示在本月的最后一个工作日触发。</p><br />\r\n\r\n            </div" +
">\r\n        </div>\r\n    </div>\r\n    <hr>\r\n    <div class=\"panel panel-info\">\r\n   " +
"     <div class=\"panel-heading\">\r\n            <h3 class=\"panel-title\">结果</h3>\r\n " +
"       </div>\r\n        <div class=\"panel-body\">\r\n            <form class=\"form-i" +
"nline\">\r\n                <div class=\"form-group\">\r\n                    <div clas" +
"s=\"input-group input-group-sm\">\r\n                        <input type=\"text\" clas" +
"s=\"form-control\" style=\"width: 450px;\" id=\"result\" placeholder=\"结果\">\r\n          " +
"              <div class=\"input-group-btn \">\r\n                            <butto" +
"n type=\"button\" id=\"analysis\" class=\"btn btn-default\"><span class=\"glyphicon gly" +
"phicon-ok\"></span>  &nbsp;反解析</button>\r\n                        </div>\r\n        " +
"            </div>\r\n                </div>\r\n            </form>\r\n        </div>\r" +
"\n    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
