#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Management.Pages
{
    
    #line 2 "..\..\Pages\JobDetailsPage.cshtml"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Pages\JobDetailsPage.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Pages\JobDetailsPage.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 5 "..\..\Pages\JobDetailsPage.cshtml"
    using Hangfire;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Pages\JobDetailsPage.cshtml"
    using Hangfire.Common;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Pages\JobDetailsPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Pages\JobDetailsPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Pages\JobDetailsPage.cshtml"
    using Hangfire.Dashboard.Resources;
    
    #line default
    #line hidden
    
    #line 10 "..\..\Pages\JobDetailsPage.cshtml"
    using Hangfire.States;
    
    #line default
    #line hidden
    
    #line 11 "..\..\Pages\JobDetailsPage.cshtml"
    using Hangfire.Storage;
    
    #line default
    #line hidden
    
    #line 12 "..\..\Pages\JobDetailsPage.cshtml"
    using Hangfire.Storage.Monitoring;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class JobDetailsPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");














            
            #line 14 "..\..\Pages\JobDetailsPage.cshtml"
  
    var monitor = Storage.GetMonitoringApi();
    var job = monitor.JobDetails(JobId);

    string title = null;

    if (job != null)
    {
        title = job.Job != null ? Html.JobName(job.Job) : null;
        job.History.Add(new StateHistoryDto { StateName = "Created", CreatedAt = job.CreatedAt ?? default(DateTime) });
    }

    title = title ?? Strings.Common_Job;
    Layout = new LayoutPage(title);


            
            #line default
            #line hidden
WriteLiteral("<div class=\"row\">\r\n    <div class=\"col-md-3\">\r\n        ");


            
            #line 31 "..\..\Pages\JobDetailsPage.cshtml"
   Write(Html.JobsSidebar());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"col-md-9\">\r\n        <h1 class=\"page-header\">");


            
            #line 34 "..\..\Pages\JobDetailsPage.cshtml"
                           Write(title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");


            
            #line 35 "..\..\Pages\JobDetailsPage.cshtml"
         if (job == null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-warning\">\r\n                ");


            
            #line 38 "..\..\Pages\JobDetailsPage.cshtml"
           Write(String.Format(Strings.JobDetailsPage_JobExpired, JobId));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 40 "..\..\Pages\JobDetailsPage.cshtml"
        }
        else
        {
            var currentState = job.History[0];
            if (currentState.StateName == ProcessingState.StateName)
            {
                var server = monitor.Servers().FirstOrDefault(x => x.Name == currentState.Data["ServerId"]);
                if (server == null)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div class=\"alert alert-danger\">\r\n                        ");


            
            #line 50 "..\..\Pages\JobDetailsPage.cshtml"
                   Write(Html.Raw(String.Format(Strings.JobDetailsPage_JobAbortedNotActive_Warning_Html, currentState.Data["ServerId"], Url.To("/servers"))));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");


            
            #line 52 "..\..\Pages\JobDetailsPage.cshtml"
                }
                else if (server.Heartbeat.HasValue && server.Heartbeat < DateTime.UtcNow.AddMinutes(-1))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div class=\"alert alert-warning\">\r\n                        ");


            
            #line 56 "..\..\Pages\JobDetailsPage.cshtml"
                   Write(Html.Raw(String.Format(Strings.JobDetailsPage_JobAbortedWithHeartbeat_Warning_Html, server.Name)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");


            
            #line 58 "..\..\Pages\JobDetailsPage.cshtml"
                }
            }

            if (job.ExpireAt.HasValue)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div class=\"alert alert-info\">\r\n                    ");


            
            #line 64 "..\..\Pages\JobDetailsPage.cshtml"
               Write(Html.Raw(String.Format(Strings.JobDetailsPage_JobFinished_Warning_Html, JobHelper.ToTimestamp(job.ExpireAt.Value), job.ExpireAt)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");


            
            #line 66 "..\..\Pages\JobDetailsPage.cshtml"
            }


            
            #line default
            #line hidden
WriteLiteral("            <div class=\"job-snippet\">\r\n                <div class=\"job-snippet-co" +
"de\">\r\n                    <pre><code><span class=\"comment\">// ");


            
            #line 70 "..\..\Pages\JobDetailsPage.cshtml"
                                                   Write(Strings.JobDetailsPage_JobId);

            
            #line default
            #line hidden
WriteLiteral(": ");


            
            #line 70 "..\..\Pages\JobDetailsPage.cshtml"
                                                                                  Write(Html.JobId(JobId.ToString(), false));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 71 "..\..\Pages\JobDetailsPage.cshtml"
Write(JobMethodCallRenderer.Render(job.Job));

            
            #line default
            #line hidden
WriteLiteral("\r\n</code></pre>\r\n                </div>\r\n");


            
            #line 74 "..\..\Pages\JobDetailsPage.cshtml"
                 if (job.Properties.Count > 0)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div class=\"job-snippet-properties\">\r\n                       " +
" <dl>\r\n");


            
            #line 78 "..\..\Pages\JobDetailsPage.cshtml"
                             foreach (var property in job.Properties.Where(x => x.Key != "Continuations"))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <dt>");


            
            #line 80 "..\..\Pages\JobDetailsPage.cshtml"
                                Write(Strings.ResourceManager.GetString("PropertyKey_" + property.Key));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n");



WriteLiteral("                                <dd><pre><code>");


            
            #line 81 "..\..\Pages\JobDetailsPage.cshtml"
                                          Write(property.Value);

            
            #line default
            #line hidden
WriteLiteral("</code></pre></dd>\r\n");


            
            #line 82 "..\..\Pages\JobDetailsPage.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </dl>\r\n                    </div>\r\n");


            
            #line 85 "..\..\Pages\JobDetailsPage.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n");


            
            #line 87 "..\..\Pages\JobDetailsPage.cshtml"

            if (job.Properties.ContainsKey("Continuations"))
            {
                List<Continuation> continuations;

                using (var connection = Storage.GetConnection())
                {
                    continuations = JobHelper.FromJson<List<Continuation>>(connection.GetJobParameter(
                        JobId, "Continuations")) ?? new List<Continuation>();
                }

                if (continuations.Count > 0)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <h3>");


            
            #line 100 "..\..\Pages\JobDetailsPage.cshtml"
                   Write(Strings.Common_Continuations);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n");



WriteLiteral("                    <div class=\"table-responsive\">\r\n                        <tabl" +
"e class=\"table\">\r\n                            <thead>\r\n                         " +
"       <tr>\r\n                                    <th class=\"min-width\">");


            
            #line 105 "..\..\Pages\JobDetailsPage.cshtml"
                                                     Write(Strings.Common_Id);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                    <th class=\"min-width\">");


            
            #line 106 "..\..\Pages\JobDetailsPage.cshtml"
                                                     Write(Strings.Common_Condition);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                    <th class=\"min-width\">");


            
            #line 107 "..\..\Pages\JobDetailsPage.cshtml"
                                                     Write(Strings.Common_State);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                    <th>");


            
            #line 108 "..\..\Pages\JobDetailsPage.cshtml"
                                   Write(Strings.Common_Job);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                    <th class=\"align-right\">");


            
            #line 109 "..\..\Pages\JobDetailsPage.cshtml"
                                                       Write(Strings.Common_Created);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                </tr>\r\n                            </thead" +
">\r\n                            <tbody>\r\n");


            
            #line 113 "..\..\Pages\JobDetailsPage.cshtml"
                                 foreach (var continuation in continuations)
                                {
                                    JobData jobData;

                                    using (var connection = Storage.GetConnection())
                                    {
                                        jobData = connection.GetJobData(continuation.JobId);
                                    }


            
            #line default
            #line hidden
WriteLiteral("                                    <tr>\r\n");


            
            #line 123 "..\..\Pages\JobDetailsPage.cshtml"
                                         if (jobData == null)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <td colspan=\"5\"><em>");


            
            #line 125 "..\..\Pages\JobDetailsPage.cshtml"
                                                           Write(String.Format(Strings.JobDetailsPage_JobExpired, continuation.JobId));

            
            #line default
            #line hidden
WriteLiteral("</em></td>\r\n");


            
            #line 126 "..\..\Pages\JobDetailsPage.cshtml"
                                        }
                                        else
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <td class=\"min-width\">");


            
            #line 129 "..\..\Pages\JobDetailsPage.cshtml"
                                                             Write(Html.JobIdLink(continuation.JobId));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");



WriteLiteral("                                            <td class=\"min-width\"><code>");


            
            #line 130 "..\..\Pages\JobDetailsPage.cshtml"
                                                                   Write(continuation.Options.ToString("G"));

            
            #line default
            #line hidden
WriteLiteral("</code></td>\r\n");



WriteLiteral("                                            <td class=\"min-width\">");


            
            #line 131 "..\..\Pages\JobDetailsPage.cshtml"
                                                             Write(Html.StateLabel(jobData.State));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");



WriteLiteral("                                            <td class=\"word-break\">");


            
            #line 132 "..\..\Pages\JobDetailsPage.cshtml"
                                                              Write(Html.JobNameLink(continuation.JobId, jobData.Job));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");



WriteLiteral("                                            <td class=\"align-right\">");


            
            #line 133 "..\..\Pages\JobDetailsPage.cshtml"
                                                               Write(Html.RelativeTime(jobData.CreatedAt));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");


            
            #line 134 "..\..\Pages\JobDetailsPage.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </tr>\r\n");


            
            #line 136 "..\..\Pages\JobDetailsPage.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </tbody>\r\n                        </table>\r\n         " +
"           </div>\r\n");


            
            #line 140 "..\..\Pages\JobDetailsPage.cshtml"
                }
            }


            
            #line default
            #line hidden
WriteLiteral("            <h3>\r\n");


            
            #line 144 "..\..\Pages\JobDetailsPage.cshtml"
                 if (job.History.Count > 1)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <span class=\"job-snippet-buttons pull-right\">\r\n              " +
"          <button class=\"btn btn-sm btn-default\" data-ajax=\"");


            
            #line 147 "..\..\Pages\JobDetailsPage.cshtml"
                                                                     Write(Url.To("/jobs/actions/requeue/" + JobId));

            
            #line default
            #line hidden
WriteLiteral("\" data-loading-text=\"");


            
            #line 147 "..\..\Pages\JobDetailsPage.cshtml"
                                                                                                                                   Write(Strings.Common_Enqueueing);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 147 "..\..\Pages\JobDetailsPage.cshtml"
                                                                                                                                                               Write(Strings.JobDetailsPage_Requeue);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                        <button class=\"btn btn-sm btn-death\" data-ajax" +
"=\"");


            
            #line 148 "..\..\Pages\JobDetailsPage.cshtml"
                                                                   Write(Url.To("/jobs/actions/delete/" + JobId));

            
            #line default
            #line hidden
WriteLiteral("\" data-loading-text=\"");


            
            #line 148 "..\..\Pages\JobDetailsPage.cshtml"
                                                                                                                                Write(Strings.Common_Deleting);

            
            #line default
            #line hidden
WriteLiteral("\" data-confirm=\"");


            
            #line 148 "..\..\Pages\JobDetailsPage.cshtml"
                                                                                                                                                                        Write(Strings.JobDetailsPage_DeleteConfirm);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 148 "..\..\Pages\JobDetailsPage.cshtml"
                                                                                                                                                                                                               Write(Strings.Common_Delete);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                    </span>\r\n");


            
            #line 150 "..\..\Pages\JobDetailsPage.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");


            
            #line 151 "..\..\Pages\JobDetailsPage.cshtml"
           Write(Strings.JobDetailsPage_State);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </h3>\r\n");


            
            #line 153 "..\..\Pages\JobDetailsPage.cshtml"

            var index = 0;

            foreach (var entry in job.History)
            {
                var accentColor = JobHistoryRenderer.GetForegroundStateColor(entry.StateName);
                var backgroundColor = JobHistoryRenderer.GetBackgroundStateColor(entry.StateName);


            
            #line default
            #line hidden
WriteLiteral("                <div class=\"state-card\" style=\"");


            
            #line 161 "..\..\Pages\JobDetailsPage.cshtml"
                                           Write(index == 0 ? $"border-color: {accentColor}" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                    <h4 class=\"state-card-title\" style=\"");


            
            #line 162 "..\..\Pages\JobDetailsPage.cshtml"
                                                    Write(index == 0 ? $"color: {accentColor}" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        <small class=\"pull-right text-muted\">\r\n");


            
            #line 164 "..\..\Pages\JobDetailsPage.cshtml"
                             if (index == job.History.Count - 1)
                            {
                                
            
            #line default
            #line hidden
            
            #line 166 "..\..\Pages\JobDetailsPage.cshtml"
                           Write(Html.RelativeTime(entry.CreatedAt));

            
            #line default
            #line hidden
            
            #line 166 "..\..\Pages\JobDetailsPage.cshtml"
                                                                   
                            }
                            else
                            {
                                var duration = Html.ToHumanDuration(entry.CreatedAt - job.History[index + 1].CreatedAt);

                                if (index == 0)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    ");

WriteLiteral(" ");


            
            #line 174 "..\..\Pages\JobDetailsPage.cshtml"
                                  Write(Html.RelativeTime(entry.CreatedAt));

            
            #line default
            #line hidden
WriteLiteral(" (");


            
            #line 174 "..\..\Pages\JobDetailsPage.cshtml"
                                                                       Write(duration);

            
            #line default
            #line hidden
WriteLiteral(")\r\n");


            
            #line 175 "..\..\Pages\JobDetailsPage.cshtml"
                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    ");

WriteLiteral(" ");


            
            #line 178 "..\..\Pages\JobDetailsPage.cshtml"
                                  Write(Html.MomentTitle(entry.CreatedAt, duration));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 179 "..\..\Pages\JobDetailsPage.cshtml"
                                }
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </small>\r\n                        ");


            
            #line 182 "..\..\Pages\JobDetailsPage.cshtml"
                    Write(Strings.ResourceManager.GetString("StateName_" + entry.StateName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </h4>\r\n");


            
            #line 184 "..\..\Pages\JobDetailsPage.cshtml"
                     if (!String.IsNullOrWhiteSpace(entry.Reason))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <p class=\"state-card-text text-muted\">");


            
            #line 186 "..\..\Pages\JobDetailsPage.cshtml"
                                                          Write(Strings.ResourceManager.GetString("Reason_" + entry.Reason));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


            
            #line 187 "..\..\Pages\JobDetailsPage.cshtml"
                    }

            
            #line default
            #line hidden

            
            #line 188 "..\..\Pages\JobDetailsPage.cshtml"
                      
                        var rendered = Html.RenderHistory(entry.StateName, entry.Data);
                    

            
            #line default
            #line hidden

            
            #line 191 "..\..\Pages\JobDetailsPage.cshtml"
                     if (rendered != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div class=\"state-card-body\" style=\"");


            
            #line 193 "..\..\Pages\JobDetailsPage.cshtml"
                                                        Write(index == 0 ? $"background-color: {backgroundColor}" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            ");


            
            #line 194 "..\..\Pages\JobDetailsPage.cshtml"
                       Write(rendered);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n");


            
            #line 196 "..\..\Pages\JobDetailsPage.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n");


            
            #line 198 "..\..\Pages\JobDetailsPage.cshtml"

                index++;
            }
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
