#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Management.Pages
{
    
    #line 2 "..\..\Pages\ManagementPage.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Pages\ManagementPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Pages\ManagementPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ManagementPage : RazorPage
    {
#line hidden

        #line 6 "..\..\Pages\ManagementPage.cshtml"

    public const string Title = "Management";
    public const string UrlRoute = "/management";

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");






WriteLiteral("\r\n");


            
            #line 10 "..\..\Pages\ManagementPage.cshtml"
  
    Layout = new LayoutPage(Title);


            
            #line default
            #line hidden
WriteLiteral("<div class=\"row\">\r\n    <div class=\"col-md-3\">\r\n        ");


            
            #line 15 "..\..\Pages\ManagementPage.cshtml"
    Write(Html.RenderPartial(new CustomSidebarMenu(ManagementSidebarMenu.Items)));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"col-md-9\">\r\n        <h1 class=\"page-header\">\r\n     " +
"       ");


            
            #line 19 "..\..\Pages\ManagementPage.cshtml"
        Write(Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </h1>\r\n        ");



WriteLiteral("\r\n        ");


            
            #line 22 "..\..\Pages\ManagementPage.cshtml"
    Write("从菜单中选择你喜欢的工作内容");

            
            #line default
            #line hidden
WriteLiteral(";\r\n    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
