#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Management.Pages
{
    
    #line 2 "..\..\Pages\ManagementBasePage.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.Linq;
    
    #line 3 "..\..\Pages\ManagementBasePage.cshtml"
    using System.Reflection;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 4 "..\..\Pages\ManagementBasePage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Pages\ManagementBasePage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class ManagementBasePage : RazorPage
    {
#line hidden

        #line 10 "..\..\Pages\ManagementBasePage.cshtml"



        #line default
        #line hidden
#line hidden
public System.Web.WebPages.HelperResult Panel(string id, string heading, string description, string content, string options, string buttons)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 14 "..\..\Pages\ManagementBasePage.cshtml"
     

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        <div class=\"panel panel-info js-management\" data-id=\"");



#line 15 "..\..\Pages\ManagementBasePage.cshtml"
                               WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n            <div class=\"panel-heading\">");



#line 16 "..\..\Pages\ManagementBasePage.cshtml"
         WriteTo(@__razor_helper_writer, heading);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</div>\r\n            <div class=\"panel-body\">\r\n                <p>");



#line 18 "..\..\Pages\ManagementBasePage.cshtml"
WriteTo(@__razor_helper_writer, description);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</p>\r\n            </div>\r\n");



#line 20 "..\..\Pages\ManagementBasePage.cshtml"
             if (!string.IsNullOrEmpty(content))
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <div class=\"panel-body\">\r\n\r\n                    <div class=\"well\"" +
">");



#line 24 "..\..\Pages\ManagementBasePage.cshtml"
        WriteTo(@__razor_helper_writer, Raw(content));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</div>\r\n\r\n                    <div id=\"");



#line 26 "..\..\Pages\ManagementBasePage.cshtml"
WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "_error\"></div>\r\n                </div>\r\n");



#line 28 "..\..\Pages\ManagementBasePage.cshtml"
            }

#line default
#line hidden



#line 29 "..\..\Pages\ManagementBasePage.cshtml"
             if (!string.IsNullOrEmpty(options))
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <div class=\"panel-body\">\r\n\r\n                    <div class=\"well\"" +
">");



#line 33 "..\..\Pages\ManagementBasePage.cshtml"
        WriteTo(@__razor_helper_writer, Raw(options));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</div>\r\n\r\n                    <div id=\"");



#line 35 "..\..\Pages\ManagementBasePage.cshtml"
WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "_error\"></div>\r\n                </div>\r\n");



#line 37 "..\..\Pages\ManagementBasePage.cshtml"
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "            <div class=\"panel-footer clearfix\">\r\n                ");



#line 39 "..\..\Pages\ManagementBasePage.cshtml"
WriteTo(@__razor_helper_writer, Raw(buttons));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\r\n                <div class=\"pull-right\">\r\n                </div>\r\n            <" +
"/div>\r\n        </div>\r\n");



#line 44 "..\..\Pages\ManagementBasePage.cshtml"

#line default
#line hidden

});

}

#line hidden
public System.Web.WebPages.HelperResult CreateButtons(string url, string text, string loadingText, string id)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 46 "..\..\Pages\ManagementBasePage.cshtml"
     

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        <div class=\"col-sm-2 pull-right commands-panel Enqueue\">\r\n            <bu" +
"tton class=\"js-management-input-commands btn btn-sm btn-success\"\r\n              " +
"      data-url=\"");



#line 49 "..\..\Pages\ManagementBasePage.cshtml"
WriteTo(@__razor_helper_writer, Url.To(url));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" data-loading-text=\"");



#line 49 "..\..\Pages\ManagementBasePage.cshtml"
                                   WriteTo(@__razor_helper_writer, loadingText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" input-id=\"");



#line 49 "..\..\Pages\ManagementBasePage.cshtml"
                                                             WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" input-type=\"Enqueue\">\r\n                <span class=\"glyphicon glyphicon-play-ci" +
"rcle\"></span>\r\n                &nbsp;列队执行\r\n            </button>\r\n        </div>" +
"\r\n");



WriteLiteralTo(@__razor_helper_writer, "        <div class=\"col-sm-8 pull-right commands-panel ScheduleDateTime\" style=\"d" +
"isplay:none\">\r\n            <div class=\"input-group input-group-sm\">\r\n           " +
"     <input type=\"text\" class=\"form-control date\" placeholder=\"Enter a date\" id=" +
"\"");



#line 56 "..\..\Pages\ManagementBasePage.cshtml"
                                                              WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "_sys_datetime\">\r\n                <div class=\"input-group-btn \">\r\n                " +
"    <button class=\"btn btn-default btn-sm btn-primary js-management-input-comman" +
"ds\" type=\"button\" input-id=\"");



#line 58 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                              WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" input-type=\"ScheduleDateTime\"\r\n                            data-url=\"");



#line 59 "..\..\Pages\ManagementBasePage.cshtml"
        WriteTo(@__razor_helper_writer, Url.To(url));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" data-loading-text=\"");



#line 59 "..\..\Pages\ManagementBasePage.cshtml"
                                           WriteTo(@__razor_helper_writer, loadingText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n                        <span class=\"glyphicon glyphicon-calendar\"></span>\r\n " +
"                       &nbsp;定时执行\r\n                    </button>\r\n              " +
"  </div>\r\n            </div>\r\n        </div>\r\n");



WriteLiteralTo(@__razor_helper_writer, "        <div class=\"col-sm-8 pull-right commands-panel ScheduleTimeSpan\" style=\"d" +
"isplay:none\">\r\n            <div class=\"input-group input-group-sm\">\r\n           " +
"     <input type=\"text\" class=\"form-control time\" placeholder=\"Enter a time 00:0" +
"0:00\" id=\"");



#line 68 "..\..\Pages\ManagementBasePage.cshtml"
                                                                       WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "_sys_timespan\" data-inputmask=\"\'mask\':\'99:99:99\'\" value=\"00:00:00\">\r\n            " +
"    <div class=\"input-group-btn \">\r\n                    <button class=\"btn btn-d" +
"efault btn-sm btn-info js-management-input-commands\" type=\"button\" input-id=\"");



#line 70 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                           WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" input-type=\"ScheduleTimeSpan\"\r\n                            data-url=\"");



#line 71 "..\..\Pages\ManagementBasePage.cshtml"
        WriteTo(@__razor_helper_writer, Url.To(url));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" data-loading-text=\"");



#line 71 "..\..\Pages\ManagementBasePage.cshtml"
                                           WriteTo(@__razor_helper_writer, loadingText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, @""">
                        <span class=""glyphicon glyphicon-time""></span>
                        &nbsp;延时执行
                    </button>
                    <button type=""button"" class=""btn btn-info btn-sm dropdown-toggle"" data-toggle=""dropdown"" aria-haspopup=""true"" aria-expanded=""false"">
                        <span class=""caret""></span>
                    </button>
                    <ul class=""dropdown-menu"">
                        <li>
                            <a href=""#"" class=""js-management-input-commands"" input-id=""");



#line 80 "..\..\Pages\ManagementBasePage.cshtml"
                                                         WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" input-type=\"ScheduleTimeSpan\" schedule=\"0:0:5\"\r\n                               " +
"data-url=\"");



#line 81 "..\..\Pages\ManagementBasePage.cshtml"
           WriteTo(@__razor_helper_writer, Url.To(url));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" data-loading-text=\"");



#line 81 "..\..\Pages\ManagementBasePage.cshtml"
                                              WriteTo(@__razor_helper_writer, loadingText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">5 秒</a>\r\n                        </li>\r\n                        <li>\r\n         " +
"                   <a href=\"#\" class=\"js-management-input-commands\" input-id=\"");



#line 84 "..\..\Pages\ManagementBasePage.cshtml"
                                                         WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" input-type=\"ScheduleTimeSpan\" schedule=\"0:0:10\"\r\n                              " +
" data-url=\"");



#line 85 "..\..\Pages\ManagementBasePage.cshtml"
           WriteTo(@__razor_helper_writer, Url.To(url));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" data-loading-text=\"");



#line 85 "..\..\Pages\ManagementBasePage.cshtml"
                                              WriteTo(@__razor_helper_writer, loadingText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">10 秒</a>\r\n                        </li>\r\n                        <li>\r\n        " +
"                    <a href=\"#\" class=\"js-management-input-commands\" input-id=\"");



#line 88 "..\..\Pages\ManagementBasePage.cshtml"
                                                         WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" input-type=\"ScheduleTimeSpan\" schedule=\"0:0:15\"\r\n                              " +
" data-url=\"");



#line 89 "..\..\Pages\ManagementBasePage.cshtml"
           WriteTo(@__razor_helper_writer, Url.To(url));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" data-loading-text=\"");



#line 89 "..\..\Pages\ManagementBasePage.cshtml"
                                              WriteTo(@__razor_helper_writer, loadingText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">15 秒</a>\r\n                        </li>\r\n                        <li>\r\n        " +
"                    <a href=\"#\" class=\"js-management-input-commands\" input-id=\"");



#line 92 "..\..\Pages\ManagementBasePage.cshtml"
                                                         WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" input-type=\"ScheduleTimeSpan\" schedule=\"0:0:30\"\r\n                              " +
" data-url=\"");



#line 93 "..\..\Pages\ManagementBasePage.cshtml"
           WriteTo(@__razor_helper_writer, Url.To(url));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" data-loading-text=\"");



#line 93 "..\..\Pages\ManagementBasePage.cshtml"
                                              WriteTo(@__razor_helper_writer, loadingText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">30 秒</a>\r\n                        </li>\r\n                        <li>\r\n        " +
"                    <a href=\"#\" class=\"js-management-input-commands\" input-id=\"");



#line 96 "..\..\Pages\ManagementBasePage.cshtml"
                                                         WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" input-type=\"ScheduleTimeSpan\" schedule=\"0:1:0\"\r\n                               " +
"data-url=\"");



#line 97 "..\..\Pages\ManagementBasePage.cshtml"
           WriteTo(@__razor_helper_writer, Url.To(url));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" data-loading-text=\"");



#line 97 "..\..\Pages\ManagementBasePage.cshtml"
                                              WriteTo(@__razor_helper_writer, loadingText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">60 秒</a>\r\n                        </li>\r\n\r\n                    </ul>\r\n         " +
"       </div>\r\n            </div>\r\n        </div>\r\n");



WriteLiteralTo(@__razor_helper_writer, @"        <div class=""col-sm-8 pull-right commands-panel CronExpression"" style=""display:none"">
            <div class=""input-group input-group-sm"">
                <input type=""text"" class=""form-control"" placeholder=""Enter a cron expression * * * * *"" id=""");



#line 106 "..\..\Pages\ManagementBasePage.cshtml"
                                                                              WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "_sys_cron\">\r\n                <div class=\"input-group-btn \">\r\n                    " +
"<button type=\"button\" class=\"btn btn-default js-management-input-CronModal\" inpu" +
"t-id=\"");



#line 108 "..\..\Pages\ManagementBasePage.cshtml"
                                                                            WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"><span class=\"glyphicon glyphicon-wrench\"></span></button>\r\n                    " +
"<button class=\"btn btn-default btn-sm btn-warning js-management-input-commands\" " +
"type=\"button\" input-id=\"");



#line 109 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                              WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" input-type=\"CronExpression\"\r\n                            data-url=\"");



#line 110 "..\..\Pages\ManagementBasePage.cshtml"
        WriteTo(@__razor_helper_writer, Url.To(url));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" data-loading-text=\"");



#line 110 "..\..\Pages\ManagementBasePage.cshtml"
                                           WriteTo(@__razor_helper_writer, loadingText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, @""">
                        <span class=""glyphicon glyphicon-repeat""></span>
                        &nbsp;重复执行
                    </button>
                    <button type=""button"" class=""btn btn-warning btn-sm dropdown-toggle"" data-toggle=""dropdown"" aria-haspopup=""true"" aria-expanded=""false"">
                        <span class=""caret""></span>
                    </button>
                    <ul class=""dropdown-menu"">
                        <li>
                            <a href=""#"" class=""js-management-input-commands"" input-id=""");



#line 119 "..\..\Pages\ManagementBasePage.cshtml"
                                                         WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" input-type=\"CronExpression\" schedule=\"");



#line 119 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                                      WriteTo(@__razor_helper_writer, Cron.Minutely());

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"\r\n                               data-url=\"");



#line 120 "..\..\Pages\ManagementBasePage.cshtml"
           WriteTo(@__razor_helper_writer, Url.To(url));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" data-loading-text=\"");



#line 120 "..\..\Pages\ManagementBasePage.cshtml"
                                              WriteTo(@__razor_helper_writer, loadingText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">每分 (");



#line 120 "..\..\Pages\ManagementBasePage.cshtml"
                                                                  WriteTo(@__razor_helper_writer, Cron.Minutely());

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, ")</a>\r\n                        </li>\r\n                        <li>\r\n             " +
"               <a href=\"#\" class=\"js-management-input-commands\" input-id=\"");



#line 123 "..\..\Pages\ManagementBasePage.cshtml"
                                                         WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" input-type=\"CronExpression\" schedule=\"");



#line 123 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                                      WriteTo(@__razor_helper_writer, Cron.Hourly());

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"\r\n                               data-url=\"");



#line 124 "..\..\Pages\ManagementBasePage.cshtml"
           WriteTo(@__razor_helper_writer, Url.To(url));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" data-loading-text=\"");



#line 124 "..\..\Pages\ManagementBasePage.cshtml"
                                              WriteTo(@__razor_helper_writer, loadingText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">每时 (");



#line 124 "..\..\Pages\ManagementBasePage.cshtml"
                                                                  WriteTo(@__razor_helper_writer, Cron.Hourly());

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, ")</a>\r\n                        </li>\r\n                        <li>\r\n             " +
"               <a href=\"#\" class=\"js-management-input-commands\" input-id=\"");



#line 127 "..\..\Pages\ManagementBasePage.cshtml"
                                                         WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" input-type=\"CronExpression\" schedule=\"");



#line 127 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                                      WriteTo(@__razor_helper_writer, Cron.Daily());

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"\r\n                               data-url=\"");



#line 128 "..\..\Pages\ManagementBasePage.cshtml"
           WriteTo(@__razor_helper_writer, Url.To(url));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" data-loading-text=\"");



#line 128 "..\..\Pages\ManagementBasePage.cshtml"
                                              WriteTo(@__razor_helper_writer, loadingText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">每天 (");



#line 128 "..\..\Pages\ManagementBasePage.cshtml"
                                                                  WriteTo(@__razor_helper_writer, Cron.Daily());

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, ")</a>\r\n                        </li>\r\n                        <li>\r\n             " +
"               <a href=\"#\" class=\"js-management-input-commands\" input-id=\"");



#line 131 "..\..\Pages\ManagementBasePage.cshtml"
                                                         WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" input-type=\"CronExpression\" schedule=\"");



#line 131 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                                      WriteTo(@__razor_helper_writer, Cron.Weekly());

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"\r\n                               data-url=\"");



#line 132 "..\..\Pages\ManagementBasePage.cshtml"
           WriteTo(@__razor_helper_writer, Url.To(url));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" data-loading-text=\"");



#line 132 "..\..\Pages\ManagementBasePage.cshtml"
                                              WriteTo(@__razor_helper_writer, loadingText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">每周 (");



#line 132 "..\..\Pages\ManagementBasePage.cshtml"
                                                                  WriteTo(@__razor_helper_writer, Cron.Weekly());

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, ")</a>\r\n                        </li>\r\n                        <li>\r\n             " +
"               <a href=\"#\" class=\"js-management-input-commands\" input-id=\"");



#line 135 "..\..\Pages\ManagementBasePage.cshtml"
                                                         WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" input-type=\"CronExpression\" schedule=\"");



#line 135 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                                      WriteTo(@__razor_helper_writer, Cron.Monthly());

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"\r\n                               data-url=\"");



#line 136 "..\..\Pages\ManagementBasePage.cshtml"
           WriteTo(@__razor_helper_writer, Url.To(url));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" data-loading-text=\"");



#line 136 "..\..\Pages\ManagementBasePage.cshtml"
                                              WriteTo(@__razor_helper_writer, loadingText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">每月 (");



#line 136 "..\..\Pages\ManagementBasePage.cshtml"
                                                                  WriteTo(@__razor_helper_writer, Cron.Monthly());

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, ")</a>\r\n                        </li>\r\n                        <li>\r\n             " +
"               <a href=\"#\" class=\"js-management-input-commands\" input-id=\"");



#line 139 "..\..\Pages\ManagementBasePage.cshtml"
                                                         WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" input-type=\"CronExpression\" schedule=\"");



#line 139 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                                      WriteTo(@__razor_helper_writer, Cron.Yearly());

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"\r\n                               data-url=\"");



#line 140 "..\..\Pages\ManagementBasePage.cshtml"
           WriteTo(@__razor_helper_writer, Url.To(url));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" data-loading-text=\"");



#line 140 "..\..\Pages\ManagementBasePage.cshtml"
                                              WriteTo(@__razor_helper_writer, loadingText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">每年 (");



#line 140 "..\..\Pages\ManagementBasePage.cshtml"
                                                                  WriteTo(@__razor_helper_writer, Cron.Yearly());

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, ")</a>\r\n                        </li>\r\n                    </ul>\r\n                " +
"</div>\r\n            </div>\r\n        </div>\r\n");



WriteLiteralTo(@__razor_helper_writer, @"        <div class=""col-sm-4"">
            <div class=""dropdown"">
                <button class=""btn btn-link dropdown-toggle"" type=""button"" id=""dropdownMenu1"" data-toggle=""dropdown"" aria-haspopup=""true"" aria-expanded=""true"">
                    任务类型: <span class=""");



#line 149 "..\..\Pages\ManagementBasePage.cshtml"
         WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, @" commandsType"">列队执行</span>
                    <span class=""caret""></span>
                </button>
                <ul class=""dropdown-menu"" aria-labelledby=""dropdownMenu1"">
                    <li><a href=""javascript:void(0)"" class=""commands-type"" data-commands-type=""Enqueue"" data-id=""");



#line 153 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                   WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">列队执行</a></li>\r\n                    <li><a href=\"javascript:void(0)\" class=\"comm" +
"ands-type\" data-commands-type=\"ScheduleDateTime\" data-id=\"");



#line 154 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                            WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">定时执行</a></li>\r\n                    <li><a href=\"javascript:void(0)\" class=\"comm" +
"ands-type\" data-commands-type=\"ScheduleTimeSpan\" data-id=\"");



#line 155 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                            WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">延时执行</a></li>\r\n                    <li><a href=\"javascript:void(0)\" class=\"comm" +
"ands-type\" data-commands-type=\"CronExpression\" data-id=\"");



#line 156 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                          WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">重复执行</a></li>\r\n                </ul>\r\n            </div>\r\n        </div>\r\n");



#line 160 "..\..\Pages\ManagementBasePage.cshtml"

#line default
#line hidden

});

}

#line hidden
public System.Web.WebPages.HelperResult Input(string id, string css, string labelText, string placeholderText, string inputtype, object defaultValue = null)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 162 "..\..\Pages\ManagementBasePage.cshtml"
     

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        <div class=\"form-group ");



#line 163 "..\..\Pages\ManagementBasePage.cshtml"
WriteTo(@__razor_helper_writer, css);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n            <label for=\"");



#line 164 "..\..\Pages\ManagementBasePage.cshtml"
WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" class=\"control-label\">");



#line 164 "..\..\Pages\ManagementBasePage.cshtml"
                       WriteTo(@__razor_helper_writer, labelText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</label>\r\n            <input class=\"form-control\" type=\"");



#line 165 "..\..\Pages\ManagementBasePage.cshtml"
                WriteTo(@__razor_helper_writer, inputtype);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" placeholder=\"");



#line 165 "..\..\Pages\ManagementBasePage.cshtml"
                                           WriteTo(@__razor_helper_writer, placeholderText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" id=\"");



#line 165 "..\..\Pages\ManagementBasePage.cshtml"
                                                                   WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" value=\"");



#line 165 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                 WriteTo(@__razor_helper_writer, defaultValue);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n        </div>\r\n");



#line 167 "..\..\Pages\ManagementBasePage.cshtml"

#line default
#line hidden

});

}

#line hidden
public System.Web.WebPages.HelperResult InputDatebox(string id, string css, string labelText, string placeholderText, object defaultValue = null)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 169 "..\..\Pages\ManagementBasePage.cshtml"
     

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        <div class=\"form-group ");



#line 170 "..\..\Pages\ManagementBasePage.cshtml"
WriteTo(@__razor_helper_writer, css);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n            <label for=\"");



#line 171 "..\..\Pages\ManagementBasePage.cshtml"
WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" class=\"control-label\">");



#line 171 "..\..\Pages\ManagementBasePage.cshtml"
                       WriteTo(@__razor_helper_writer, labelText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</label>\r\n            <div class=\'input-group date\' id=\'");



#line 172 "..\..\Pages\ManagementBasePage.cshtml"
                WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "_datetimepicker\'>\r\n                <input type=\'text\' class=\"form-control\" placeh" +
"older=\"");



#line 173 "..\..\Pages\ManagementBasePage.cshtml"
                                       WriteTo(@__razor_helper_writer, placeholderText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" value=\"");



#line 173 "..\..\Pages\ManagementBasePage.cshtml"
                                                                  WriteTo(@__razor_helper_writer, defaultValue);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" />\r\n                <span class=\"input-group-addon\">\r\n                    <span" +
" class=\"glyphicon glyphicon-calendar\"></span>\r\n                </span>\r\n        " +
"    </div>\r\n        </div>\r\n");



#line 179 "..\..\Pages\ManagementBasePage.cshtml"

#line default
#line hidden

});

}

#line hidden
public System.Web.WebPages.HelperResult InputCheckbox(string id, string css, string labelText, string placeholderText)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 181 "..\..\Pages\ManagementBasePage.cshtml"
     

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        <div class=\"form-group ");



#line 182 "..\..\Pages\ManagementBasePage.cshtml"
WriteTo(@__razor_helper_writer, css);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n            <div class=\"checkbox\">\r\n                <label>\r\n                " +
"    <input type=\"checkbox\" id=\"");



#line 185 "..\..\Pages\ManagementBasePage.cshtml"
                 WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n                    ");



#line 186 "..\..\Pages\ManagementBasePage.cshtml"
WriteTo(@__razor_helper_writer, labelText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\r\n                </label>\r\n            </div>\r\n        </div>\r\n");



#line 190 "..\..\Pages\ManagementBasePage.cshtml"

#line default
#line hidden

});

}

#line hidden
public System.Web.WebPages.HelperResult InputDataList(string id, string css, string labelText, string placeholderText, KeyValuePair<string, string>[] data, string defaultValue = null)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 192 "..\..\Pages\ManagementBasePage.cshtml"
     

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        <div class=\"form-group ");



#line 193 "..\..\Pages\ManagementBasePage.cshtml"
WriteTo(@__razor_helper_writer, css);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n            <label for=\"");



#line 194 "..\..\Pages\ManagementBasePage.cshtml"
WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" class=\"control-label\">");



#line 194 "..\..\Pages\ManagementBasePage.cshtml"
                       WriteTo(@__razor_helper_writer, labelText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</label>\r\n            <select id=\"");



#line 195 "..\..\Pages\ManagementBasePage.cshtml"
WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" class=\"form-control\" placeholder=\"");



#line 195 "..\..\Pages\ManagementBasePage.cshtml"
                                   WriteTo(@__razor_helper_writer, placeholderText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n");



#line 196 "..\..\Pages\ManagementBasePage.cshtml"
                 foreach (var item in data)
                {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                    <option value=\"");



#line 198 "..\..\Pages\ManagementBasePage.cshtml"
    WriteTo(@__razor_helper_writer, item.Key);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" ");



#line 198 "..\..\Pages\ManagementBasePage.cshtml"
                WriteTo(@__razor_helper_writer, item.Key == defaultValue ? "selected=\"selected\"" : "");

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, ">");



#line 198 "..\..\Pages\ManagementBasePage.cshtml"
                                                                          WriteTo(@__razor_helper_writer, item.Value);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</option>\r\n");



#line 199 "..\..\Pages\ManagementBasePage.cshtml"
                }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "            </select>\r\n        </div>\r\n");



#line 202 "..\..\Pages\ManagementBasePage.cshtml"

#line default
#line hidden

});

}


        public override void Execute()
        {


WriteLiteral("\r\n");







            
            #line 7 "..\..\Pages\ManagementBasePage.cshtml"
  
    Layout = new LayoutPage(pageTitle);


            
            #line default
            #line hidden

WriteLiteral("\r\n");



WriteLiteral("\r\n");



WriteLiteral("\r\n");



WriteLiteral("\r\n");



WriteLiteral("\r\n");



WriteLiteral("\r\n");



WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"col-md-3\">\r\n        ");


            
            #line 205 "..\..\Pages\ManagementBasePage.cshtml"
    Write(Html.RenderPartial(new CustomSidebarMenu(ManagementSidebarMenu.Items)));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"col-md-9\">\r\n        <h1 class=\"page-header\">\r\n     " +
"       ");


            
            #line 209 "..\..\Pages\ManagementBasePage.cshtml"
        Write(pageHeader);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </h1>\r\n");


            
            #line 211 "..\..\Pages\ManagementBasePage.cshtml"
          
            Content();
        

            
            #line default
            #line hidden
WriteLiteral(@"    </div>

    <div class=""modal fade"" id=""cronModal"" tabindex=""-1"" role=""dialog"" aria-labelledby=""cronModalLabel"">
        <div class=""modal-dialog"" role=""document"">
            <div class=""modal-content"">
                <div class=""modal-header"">
                    <button type=""button"" class=""close"" data-dismiss=""modal"" aria-label=""Close""><span aria-hidden=""true"">&times;</span></button>
                    <h4 class=""modal-title"" id=""cronModalLabel"">Corn表达式生成器</h4>
                </div>
                <div class=""modal-body"">
                    ");


            
            #line 224 "..\..\Pages\ManagementBasePage.cshtml"
                Write(Html.RenderPartial(new CornJobsPage()));

            
            #line default
            #line hidden
WriteLiteral(@"
                </div>
                <div class=""modal-footer"">
                    <button type=""button"" class=""btn btn-default"" data-dismiss=""modal"">关闭</button>
                    <button type=""button"" class=""btn btn-primary"" id=""connExpressionOk"">确定</button>
                </div>
            </div>
        </div>
    </div>
</div>
");




        }
    }
}
#pragma warning restore 1591
